#!/bin/bash

################## Configuration ########################################
KEY_NAME="MyKeyPair"
SECURITY_GROUP_NAME="MySecurityGroup"
AMI_ID="ami-0abcdef1234567890" #Replace with a valid AMI ID in your region
INSTANCE_TYPE="t3.micro"

################## Create Key Pair ########################################
aws ec2 create-key-pair --key-name $KEY_NAME --query 'KeyMaterial' --output text > ${KEY_NAME}.pem
chmod 400 ${KEY_NAME}.pem

################## Create Security Group ########################################
SECURITY_GROUP_ID=$(aws ec2 create-security-group --group-name $SECURITY_GROUP_NAME --description "Security group for t3.micro instance" --query 'GroupId' --output text)
echo "Security Group ID: $SECURITY_GROUP_ID"

################## Authorize Security Group Ingress ########################################
aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 22 --cidr 0.0.0.0/0

################## Launch EC2 Instance ########################################
INSTANCE_ID=$(aws ec2 run-instances --image-id $AMI_ID --count 1 --instance-type $INSTANCE_TYPE --key-name $KEY_NAME --security-group-ids $SECURITY_GROUP_ID --query 'Instances[0].InstanceId' --output text)
echo "Instance ID: $INSTANCE_ID"

################## Describe EC2 Instances ########################################
aws ec2 describe-instances --instance-ids $INSTANCE_ID


### ---------------------------------------------------------------------
### Other Operations
### ---------------------------------------------------------------------

################## Start EC2 Instance ########################################
# aws ec2 start-instances --instance-ids $INSTANCE_ID
# echo "Instance $INSTANCE_ID started."

########### Stop EC2 Instance ############################################
# aws ec2 stop-instances --instance-ids $INSTANCE_ID
# echo "Instance $INSTANCE_ID stopped."

########### Reboot EC2 Instance ############################################
# aws ec2 reboot-instances --instance-ids $INSTANCE_ID
# echo "Instance $INSTANCE_ID rebooted."

########### Terminate EC2 Instance ############################################
# aws ec2 terminate-instances --instance-ids $INSTANCE_ID
# echo "Instance $INSTANCE_ID terminated."

########### Delete Security Group ############################################
# aws ec2 delete-security-group --group-id $SECURITY_GROUP_ID
# echo "Security Group $SECURITY_GROUP_ID deleted."

########### Delete Key Pair ############################################
# aws ec2 delete-key-pair --key-name $KEY_NAME
# echo "Key Pair $KEY_NAME deleted."
# rm -f ${KEY_NAME}.pem

# echo "All operations completed."
